export const SUCCESS = "SUCCESS";
export const FAIL = "FAIL";
export const FORBIDDEN = "NO PERMISSION TO ACCESS THIS FUNCTION";
export const LIST_PARTICIPANT_FORBIDDEN = "NO PERMISSION TO ADD PARTICIPANTS TO ACTIVITY";
export const MESS_INTERNAL_SERVER_ERROR = "INTERNAL SERVER ERROR";

export enum FAIL_MESSAGE {
    GETALL = "FAILED TO GET ALL DATA",
    GETID = "FAILED TO GET DATA BY ID",
    CREATE = "FAILED TO CREATE DATA",
    EDIT = "FAILED TO EDIT DATA",
    DELETE = "FAILED TO DELETE DATA",
    CATCH_DATA = "FAILED TO FETCH DATA BY ID",
    UNIDENTIFY = "UNKNOWN ID: ",
    PARTICIPANT = "FAILED TO GET PARTICIPANTS",
    LIST_ACTIVITY_IN_GROUP_UNIONDEPT = "FAILED TO GET ACTIVITIES IN UNIONDEPT GROUP",
    LIST_ACTIVITY_IN_GROUP_PARTICIPANT = "FAILED TO GET ACTIVITIES IN PARTICIPANT GROUP"
}

export enum ERROR_DB {
    CATEGORY_NOTFOUND = "CATEGORY ID NOT FOUND: ",
    UNIQUE_CONSTRAINT = "DATABASE UNIQUE CONSTRAINT VIOLATION",
    ACTIVITY_NOTFOUND = "ACTIVITY ID NOT FOUND: ",
    UNIONDEPT_NOTFOUND = "UNIONDEPT ID NOT FOUND: ",
    USER_NOTFOUND = "USER ID NOT FOUND: ",
    PARTICIPANT_NOTFOUND = "PARTICIPANT ID NOT FOUND: "
}
