variables:
  PROJECT_NAME: $CI_PROJECT_NAME
  DOCKER_TAG: lastest
  DOCKER_NETWORK: "congdoan-network"
  SECURE_FILENAME: ".env"

stages:
  - build
  - get-env
  - deploy

build_image:
  variables:
    GIT_STRATEGY: clone
  stage: build
  script:
    - echo "Building docker image..."
    - ls
    - cd backend
    - docker build -t ${PROJECT_NAME}:${DOCKER_TAG} .

  only:
    - staging
  tags:
    - congdoan-server

download_secure_files:
  stage: get-env
  variables:
    SECURE_FILES_DOWNLOAD_PATH: "./env"
    GIT_STRATEGY: none
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
  only:
    - staging
  tags:
    - congdoan-server

deploy_app:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo ${PROJECT_NAME}:${DOCKER_TAG}
    - echo ${DOCKER_NETWORK}
    - echo "removing old container..."
    - docker rm -f ${CI_PROJECT_NAME}
    - echo "Running docker container..."
    - cd backend
    - cat ../env/${SECURE_FILENAME}
    - docker run -d
      --name ${PROJECT_NAME}
      --env-file ../env/${SECURE_FILENAME}
      --network ${DOCKER_NETWORK}
      -p 4000:4000
      ${PROJECT_NAME}:${DOCKER_TAG}

    - echo "Running container successfully, access it at port 4000."
  only:
    - staging
  tags:
    - congdoan-server
